[package]
name = "ferox"
description = "Ferox is a ray-tracing renderer written in Rust." 
license = "CC0-1.0" 
version = "0.3.0"
edition = "2024"

[dependencies]
glam = "0.30.1"
image = "0.25.5"

[[bin]]
name = "ferox"
path = "main.rs"
