[package]
name = "ferox"
description = "Ferox is a ray-tracing renderer written in Rust." 
repository = "https://github.com/adharmic/ferox"
license = "CC0-1.0" 
version = "0.4.4"
edition = "2024"

[dependencies]
glam = "0.30.1"
image = "0.25.5"

[[bin]]
name = "ferox"
path = "src/main.rs"
